- name: Deploy code to AWS instance
  hosts: all
  become: yes  # This will allow us to run tasks with elevated privileges
  tasks:
    - name: Clone repository
      git:
        repo: 'https://github.com/Gagan-R31/demo.git'  # Replace with your GitHub repo URL
        dest: /var/www/demo/  # Replace with the path where you want to clone the repo on your AWS instance
        version: master  # Replace with the branch you want to clone
      register: clone_result  # This registers the result of the clone task for later use

    - name: Display clone result
      debug:
        var: clone_result  # This task will display the result of the clone task

    - name: Remove demo directory
      file:
        path: /var/www/demo/  # Path to the directory you want to remove
        state: absent  # Ensures the directory and its contents are removed
      when: clone_result.changed  # Runs only if the repository was cloned or updated
