name: Docker Build and Deploy

on:
  push:
    branches: [ master ]  

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: gaganr31
        password: Gagan@4882

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: gaganr31/demo

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo docker pull yourdockerhubusername/your-repo-name:latest
          sudo docker stop my-website-container || true
          sudo docker rm my-website-container || true
          sudo docker run -d --name demo -p 8080:80 gaganr31/demo
