name: Display .env File

on:
  push:
    branches:
      - master

jobs:
  display-env:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Fetch the .env file from GitHub Secrets
      - name: Set up .env file
        run: echo "${{ secrets.ENV }}" > .env

      # Step 3: Display the .env file contents
      - name: Display .env content
        run: cat .env
        
